### ISSUE TITLE
How to run the test cases.

### ISSUE THREAD

**Issue by Rahulgarg30591** [rcogal/extjs-jasmine#1]
Hello @rcogal,

Thank you for the repo. I am using Ext6.6 and created the workspace.

These are the steps I followed.

1.) I created a folder(senchaTest) where I will keep my workspace.
2.) Copied Ext 6.6.0 in this folder.
3.) Created the workspace using the command from the ext folder: 

> sencha generate workspace ../workspace.

4.) Workspace is created cleanly.
5.) Downloaded your project from https://github.com/rcogal/extjs-jasmine and put the content inside the workspace.
6.) Updated the frameworks of Sencha in workspace.json to 6.6.0.258.
7.) Moved back to the extFolder, and ran this command:

> sencha generate app --ext  MyApp ../MyApp

8.) Checked the steps 4, 5, 6, and 7 as per the readme of your project.

When I run

> sencha web start 

No spec is running.

Thank you for reading this. Will be waiting for the response. Thanks again.

**Comment by rcogal** [comment]
Hi @Rahulgarg30591 ,

I will changed the documentation for better understanding. It's actually running but there are missing steps that I forgot to specify.

I'm glad I helped you earlier. 

Thank you.
